### ISSUE TITLE
Can not connect a Facebook/Instagram channel.

### ISSUE THREAD

**Issue by Gloria0805** [nyaruka/rapidpro#4279]
**Describe the bug**
When adding my Facebook channel I am taken to Facebook page saying "app not active"
**To Reproduce**
1. Log into my Facebook account
2. Clicking “add Facebook page” from textit

**Expected behavior**
Being taken to Facebook to confirm my login, then select a page to connect to textit.

**Screenshots**
<img width="1283" alt="Screen Shot 2023-01-23 at 14 24 53" src="https://user-images.githubusercontent.com/124047613/215752309-1262d0e1-025b-47f6-932d-7ff1a5a8167d.png">

**Browser:**
 Chrome
Safari

**Additional context**
Same error when adding Instagram channel

**Comment by ericnewcomer** [comment]
Fixed
