### ISSUE TITLE
Channel types extra views not using new UI

### ISSUE THREAD

**Issue by norkans7** [nyaruka/rapidpro#4281]
**Describe the bug**
New UI not supported for WhatsApp templates page and sync logs page
URL as `/channels/types/whatsapp_cloud/[UUID]/sync_logs` `/channels/types/whatsapp_cloud/[UUID]/templates`
So any extra views in the channel types

**To Reproduce**
1. Go to a WhatsApp channel 
2. Click on the menu
3. Choose message templates
4. Get page with the old UI

**Expected behavior**
The page to be using the new UI

**Screenshots**
<img width="1504" alt="Monosnap RapidPro - Visually build nationally scalable mobile applications 2023-01-31 19-35-30" src="https://user-images.githubusercontent.com/1040571/215839021-73b3b3a4-b7be-4872-af28-3d3ee246c2c2.png">

**Desktop (please complete the following information):**
Chrome 

**Additional context**
None

**Comment by ericnewcomer** [comment]
Fixed
