### ISSUE TITLE
Enable country location in flows

### ISSUE THREAD

**Issue by Gloria0805** [nyaruka/rapidpro#4285]
**Describe the bug**
When choosing a country used for location value, there is no drop-down appearing. 

**To Reproduce**
1. Go to 'settings page'
2. Click on 'Choose a country to enable location support in flows'
3. Click the input bar 

**Expected behavior**
Have a drop-down of countries to choose from.
**Screenshots**

https://user-images.githubusercontent.com/124047613/216328678-ee83bc2b-8bd4-4386-9266-b3d2f6b7d0b7.mp4

**Browser:**
 -Safari
 -chrome 

**Additional context**
none

**Comment by norkans7** [comment]
This should be fixed, I imported locations data
