### ISSUE TITLE
External links for channel claim page are not working

### ISSUE THREAD

**Issue by Gloria0805** [nyaruka/rapidpro#4296]
**Describe the bug**
When clicking on the external link the page keeps loading.
**To Reproduce**
1. Go to 'settings'
2. Click 'new channel' 
3. Click on 'telegram
4. click the embedded link

**Expected behavior**
Taking me to the embedded link page

**Screenshots**

https://user-images.githubusercontent.com/124047613/217559700-fd3ff9e6-4620-4313-81a3-6c5802da3bd9.mp4

**Desktop **
 - Browser [chrome, safari]

**Additional context**
Same behavior for:  
Twilio, 
Twilio messaging service, 
Facebook, 
Instagram, 
Africa's talking, 
Twilio whatsapp, 
360Dialog WhatsApp, 
Zenvia WhatsApp, 
discord, 
Jiochat, 
Kaleyra WhatsApp, 
LINE, 
Rocket.Chat, 
Twitter, 
Viber, 
VK, 
Wechat, 
Bandwidth, 
Clickatell, 
I2SMS, 
Infobid, 
Jasmin, 
Junebug, 
Justcall, 
Kannel, 
Mblox, 
Pilvo, 
Zenvia SMS,
Firebase Cloud Messaging, 
FreshChat

**Comment by ericnewcomer** [comment]
Fixed
