### ISSUE TITLE
Screen freezes while seeing revision history 

### ISSUE THREAD

**Issue by mdshamoon** [nyaruka/rapidpro#4303]
**Describe the bug**
When seeing the revision history, the screen freezes and i can't scroll to see the nodes below

**To Reproduce**

1. Click on revision history button
2. Select one time stamp

**Expected behavior**
It should allow me to scroll to see other nodes

**Screenshots**
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/32592458/217978690-8432d7fe-c4a9-4688-945d-62c998b2f3bd.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura  13.1
 - Browser: Chrome 109

**Comment by ericnewcomer** [comment]
We'd be willing to accept a PR to address this @mdshamoon. Scrolling can be allowed so long as other pointer events are ignored appropriately.
