### ISSUE TITLE
Save flow results is not working in the new UI

### ISSUE THREAD

**Issue by Gloria0805** [nyaruka/rapidpro#4328]
**Describe the bug**
While saving a result in my flow using addition, the action did not execute. 
The next action as well, the contact completed the flow. 
**To Reproduce**
1. Create the flow 
2. Collect a number and name the results (results.score)
3. Go to 'Save flow results'
4. Click on the 'result drop-down' and select the saved results (score)
5. Click on value and enter '@(results.score + 1)' and click ok
6. Send a message '@results.score'
7. Start the flow
8. See error

**Expected behavior**
When starting the flow I expect to enter a number, and the flow to return the same number + 1
**Screenshots**
No screenshot
**Desktop**
 - Browser chrome, safari
 

**Additional context**

**Comment by ericnewcomer** [comment]
I can't reproduce this one. Here is the flow I created (as best as I can interpret the steps)

https://textit.staging.nyaruka.com/flow/editor/40a79001-b456-47d9-b22f-7ea221f060d6/

<img width="271" alt="Screenshot 2023-02-28 at 2 03 20 PM" src="https://user-images.githubusercontent.com/211652/221991845-e86173da-740b-482d-ab75-f9fede2838e6.png">

<img width="358" alt="Screenshot 2023-02-28 at 2 04 44 PM" src="https://user-images.githubusercontent.com/211652/221992126-c5bfc7d3-c0fa-4181-8d47-0ac431ea887a.png">

**Comment by Gloria0805** [comment]
I am resting now.

**Comment by Gloria0805** [comment]
Can not reproduce, Closing this.
