### ISSUE TITLE
Switch to using POST messages.json for single message sends

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/rapidpro#4348]
Like on the chat widget on contact read pages, or ticket pages. Instead of POSTing to broadcasts.json.

**Comment by susanm74** [comment]
@rowanseymour ok i think this one is mostly clear, but do we expect this update to be needed across both the floweditor and temba-components repos? i think there are some scenarios where something in a flow could result in a "single messsage send" ex. if a flow contains the send msg node and only specifies one contact? also, i think in the old ui there is a "send message" button which brings up a modal specifying just the one contact?... so yeah, just want to confirm what's included in the scope of the work...

and then below are just a few quick questions to sanity check any discrepancies with the work across repos, the old vs. new ui and to also snag any relevant navigation steps/links to more quickly zero in on where the change needs to happen:

floweditor vs. temba-components
- updates needed in only floweditor?
- updates needed in only temba-components?
- updates needed in both?

old vs new ui
- change needed for only new ui? (no affect to old ui)
- change needed for "both" new ui and old ui? (needs to maintain status quo display/behavior of old ui)
- change needed for both new ui and old ui? (will result in a change of display/behavior in old ui)

navigation
- how to navigate to where changed is needed in new ui?
- how to navigate to where changed is needed in old ui?

thanks for bearing with on the above!

**Comment by ericnewcomer** [comment]
One issue with this is that we probably want a `created_by` on `Msg` before making this change. This is pretty important in the ticketing view to see which agent sent which message. Today, this uses `Broadcast.created_by`

**Comment by rowanseymour** [comment]
@ericnewcomer good point - just made https://github.com/nyaruka/rapidpro/pull/4379 and https://github.com/nyaruka/mailroom/pull/44
