### ISSUE TITLE
Missing Channel Icons

### ISSUE THREAD

**Issue by LeahBreedenNyaruka** [nyaruka/rapidpro#4350]
When looking at a channel page in new interface, not all icons appear as they should.

1. Go to [this channel](https://app.rapidpro.io/channels/channel/read/9cec1fc0-5dfc-4983-b296-8b6501e5e58e/) or [this one](https://app.rapidpro.io/channels/channel/read/f429a624-01c2-4b0a-a34d-408caf30b699/) in U-Report Ukraine.
2. See icon

<img width="294" alt="Screen Shot 2023-02-23 at 2 48 58 PM" src="https://user-images.githubusercontent.com/60149838/221016225-e85cb231-8a6a-4d87-9f74-66dab76c552c.png">

 -  iOS
 - Browser Chrome
 - Version 107.0.5304.121

**Comment by ericnewcomer** [comment]
Fixed
