### ISSUE TITLE
Broken refresh after labelling messages

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/rapidpro#4358]
**To Reproduce**
1. Go to `Failed` messages
2. Go to `Flows` messages
3. Label a message

The message list refreshes to show `Failed` messages, but the page title says `Flows`

**Comment by ericnewcomer** [comment]
@rowanseymour can you shift-refresh? I think you might have an out of date labels.js file. If this is the case we need to make sure it is compressed for cache busting.
