### ISSUE TITLE
Help button doesn't work on Chrome (new UI)

### ISSUE THREAD

**Issue by Gloria0805** [nyaruka/rapidpro#4366]
**Describe the bug**
The help window does not show up after clicking help

**To Reproduce**
1. Log into your workspace in chrome
2. Click on the 'Help' icon
3. See error

**Expected behavior**
Help window to open so I chat with an agent

**Screenshots**
<img width="108" alt="Screen Shot 2023-03-01 at 14 27 18" src="https://user-images.githubusercontent.com/124047613/222139978-c2bb73e9-0682-4e1f-bcd4-d900ea5fe9f4.png">

**Desktop:**
 - Browser: chrome

**Additional context**
None

**Comment by ericnewcomer** [comment]
Not seeing this, could maybe have been a temporary issue with Crisp. Are you still seeing this @Gloria0805 ?

**Comment by Gloria0805** [comment]
It is still happening for me on chrome, here is a screencast;

Uploading screencast 2023-03-02 15-20-41.mp4…
