### ISSUE TITLE
When updating contacts in bulk, it duplicates the URN field

### ISSUE THREAD

**Issue by eochieng-lab** [nyaruka/rapidpro#4378]
**Describe the bug**
When updating contact fields in bulk using the Import Contacts feature on RapidPro, the contacts are updated but it appears to duplicate the URN field. This happens when a contact's URN value is updated.
![image](https://user-images.githubusercontent.com/77043654/222656213-4a26d00a-a5af-400e-b51b-6cad84b930af.png)

**To Reproduce**
1. Go to the **Contacts** page
2. Export the contacts
3. On the Excel sheet, update one of the contact fields which is a URN field
4. Import the Excel file back to RapidPro
5. There will be two URN fields created as shown in the screenshot above

**Expected behavior**
It should replace the contact field that was updated

**Comment by norkans7** [comment]
Hey @eochieng-lab, this is intentional.

URNs are appended to the existing one we do not replace/remove the existing one in bulk

**Comment by norkans7** [comment]
You can update contact fields and even clear them by using `--` however urns are append only on contacts imports

**Comment by eochieng-lab** [comment]
Makes sense. Thanks @norkans7
