### ISSUE TITLE
Allow deleting of individual archived triggers

### ISSUE THREAD

**Issue by susanm74** [nyaruka/rapidpro#4481]
- Deleting the trigger should warn the user first and ask to confirm or cancel
   - If there’s a flow, and there’s a trigger for that flow, we should allow deleting the flow and delete the trigger along with it
- Ex to model deleting triggers off of - deleting a field
- No need to delete anything besides the trigger

**Comment by rowanseymour** [comment]
To clarify - deleting a trigger should have no effect on the associated flow. Deleting a flow already deletes any associated triggers.

**Comment by susanm74** [comment]
<img width="1264" alt="Screen Shot 2023-04-26 at 11 11 22 AM" src="https://user-images.githubusercontent.com/854012/234468045-f00f4a46-e5bc-486e-b539-9ea91c8ca656.png">
<img width="623" alt="Screen Shot 2023-04-26 at 11 11 29 AM" src="https://user-images.githubusercontent.com/854012/234468053-a1301279-0ec5-4392-a80f-2f97e01e44eb.png">

**Comment by susanm74** [comment]
closing in favor of https://github.com/nyaruka/rapidpro/issues/4520 and https://github.com/nyaruka/rapidpro/issues/4550
