### ISSUE TITLE
Group Deletion

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/rapidpro#4485]
### Discussed in https://github.com/nyaruka/rapidpro/discussions/4372

<div type='discussions-op-text'>

<sup>Originally posted by **ericnewcomer** March  1, 2023</sup>
Users should be able to delete groups and face the consequences of that later.

This implies:
  * Campaigns existing without groups (and having a 'issues'?)
  * Triggers either dropping groups designations or keeping them with an issue
  * Probably other things I'm not thinking of</div>

**Comment by rowanseymour** [comment]
Added in #4473
