### ISSUE TITLE
/org/choose/ still needs jQuery

### ISSUE THREAD

**Issue by matlads** [nyaruka/rapidpro#5214]
**jQuery is still needed**
the path `/org/choose/` throws these errors in the console

```
Uncaught ReferenceError: $ is not defined
    posterize /sitestatic/js/frame.js:565
    handlePosterize /sitestatic/js/frame.js:580
    handlePosterizeClick /sitestatic/js/frame.js:586
    onclick Choo
```
**To Reproduce**
1. install `rapidpro-9.1.96 or later`
2. Login
3. Bring up the browser's inspect console
4. Click on any org
5. See error

**Expected behavior**
I expected the redirect to happen

**Desktop (please complete the following information):**
 - OS: macosx
 - Browser:  Firefox 
 - Version: 125.0.2

**Additional context**
N/A

**Comment by ericnewcomer** [comment]
Thanks for the detailed report, we'll have a look!

**Comment by ericnewcomer** [comment]
I'm unable to reproduce this. I think may have been addressed already. Can you share the block of code where you are seeing that error on your install to confirm it's the same as what I'm testing with?

jQuery was removed in 9.1.96 and then a minor fix was applied specifically for the org chooser in 9.1.97 (but this had to do with relative urls, not existence of $ like your bug report suggests)

https://github.com/nyaruka/rapidpro/releases/tag/v9.1.97

**Comment by matlads** [comment]
While attempting to resolve this issue, I updated to v9.1.100 and removed `node_modules` and rebuilt using `npm install`, and these steps seem to have resolved my issue.

Thanks for your help.
